/**
 * ConfFlow Build Script
 * Injects Firebase env vars from Vercel environment into firebase-config.js
 * Supports both FIREBASE_* (your Vercel setup) and VITE_FIREBASE_* prefixes
 */

const fs   = require('fs');
const path = require('path');

// ── Helper: read env var trying multiple prefixes ─────────
function env(key) {
  return process.env[key]
    || process.env['VITE_' + key]
    || process.env['NEXT_PUBLIC_' + key]
    || '';
}

// ── Inject config into firebase-config.js ────────────────
function injectFirebaseConfig() {
  const configPath = path.join(__dirname, 'firebase-config.js');

  const apiKey           = env('FIREBASE_API_KEY');
  const authDomain       = env('FIREBASE_AUTH_DOMAIN');
  const projectId        = env('FIREBASE_PROJECT_ID');
  const storageBucket    = env('FIREBASE_STORAGE_BUCKET');
  const messagingSenderId= env('FIREBASE_MESSAGING_SENDER_ID');
  const appId            = env('FIREBASE_APP_ID');
  const measurementId    = env('FIREBASE_MEASUREMENT_ID') || '';

  if (!apiKey) {
    console.warn('⚠️  FIREBASE_API_KEY not found in environment. firebase-config.js will not be updated.');
    console.warn('   Make sure you have set FIREBASE_API_KEY in your Vercel Environment Variables.');
    return false;
  }

  const configContent = `// firebase-config.js — AUTO-GENERATED by build.js, do not edit manually
// Generated at: ${new Date().toISOString()}
window.__FIREBASE_CONFIG__ = {
  apiKey:            "${apiKey}",
  authDomain:        "${authDomain}",
  projectId:         "${projectId}",
  storageBucket:     "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId:             "${appId}",
  measurementId:     "${measurementId}"
};
`;

  fs.writeFileSync(configPath, configContent, 'utf8');
  console.log('  ✓ firebase-config.js updated with environment variables');
  return true;
}

async function build() {
  console.log('\n🚀 ConfFlow Build Starting...\n');

  const injected = injectFirebaseConfig();

  if (injected) {
    console.log('\n✅ Build complete — firebase-config.js is ready for deployment');
  } else {
    console.log('\n⚠️  Build completed but Firebase config was NOT injected (missing env vars)');
    console.log('   The app will use whatever values are currently in firebase-config.js');
  }

  const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
  console.log(`📦 ConfFlow v${pkg.version}`);
  console.log(`🌐 Deploy: vercel --prod\n`);
}

build().catch(console.error);
