/**
 * build.js — Runs at Vercel build time.
 * Reads FIREBASE_* environment variables (set in Vercel dashboard)
 * and writes a firebase-config.js file that the browser can load.
 *
 * HOW TO USE:
 * 1. In Vercel dashboard → Project → Settings → Environment Variables, add:
 *      FIREBASE_API_KEY
 *      FIREBASE_AUTH_DOMAIN
 *      FIREBASE_PROJECT_ID
 *      FIREBASE_STORAGE_BUCKET
 *      FIREBASE_MESSAGING_SENDER_ID
 *      FIREBASE_APP_ID
 *      FIREBASE_MEASUREMENT_ID   (optional)
 *
 * 2. In Vercel dashboard → Project → Settings → Build & Output Settings:
 *      Build Command:    node build.js
 *      Output Directory: .
 *
 * 3. In your index.html, add this BEFORE firebase.js loads:
 *      <script src="/firebase-config.js"></script>
 *
 * 4. In firebase.js, read config from window.__FIREBASE_CONFIG__ instead
 *    of hardcoded values. Example:
 *      const firebaseConfig = window.__FIREBASE_CONFIG__;
 */

const fs = require('fs');
const path = require('path');

// Read from env (set in Vercel dashboard — never from .env in the repo)
const config = {
  apiKey:            process.env.FIREBASE_API_KEY            || '',
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN        || '',
  projectId:         process.env.FIREBASE_PROJECT_ID         || '',
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET     || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID|| '',
  appId:             process.env.FIREBASE_APP_ID             || '',
  measurementId:     process.env.FIREBASE_MEASUREMENT_ID     || '',
};

// Validate that required keys are present
const required = ['apiKey', 'authDomain', 'projectId', 'appId'];
const missing = required.filter(k => !config[k]);
if (missing.length > 0) {
  console.error('❌ Build failed: Missing required Firebase env vars:', missing.join(', '));
  console.error('   Add them in Vercel Dashboard → Settings → Environment Variables');
  process.exit(1);
}

// Write a JS file that exposes config globally in the browser
const output = `// Auto-generated by build.js — DO NOT EDIT
// Firebase config injected from Vercel environment variables at build time
window.__FIREBASE_CONFIG__ = ${JSON.stringify(config, null, 2)};
`;

const outPath = path.join(__dirname, 'firebase-config.js');
fs.writeFileSync(outPath, output, 'utf8');

console.log('✅ firebase-config.js generated successfully');
console.log('   Project ID:', config.projectId);
