/**
 * ConfFlow Build Script
 * Reads Firebase env vars set in Vercel dashboard and writes firebase-config.js
 * Supports: FIREBASE_* (your setup) and VITE_FIREBASE_* prefixes
 */

const fs   = require('fs');
const path = require('path');

function env(key) {
  return (
    process.env[key] ||
    process.env['VITE_' + key] ||
    ''
  );
}

function build() {
  console.log('\n🚀 ConfFlow Build Starting...\n');

  const apiKey            = env('FIREBASE_API_KEY');
  const authDomain        = env('FIREBASE_AUTH_DOMAIN');
  const projectId         = env('FIREBASE_PROJECT_ID');
  const storageBucket     = env('FIREBASE_STORAGE_BUCKET');
  const messagingSenderId = env('FIREBASE_MESSAGING_SENDER_ID');
  const appId             = env('FIREBASE_APP_ID');
  const measurementId     = env('FIREBASE_MEASUREMENT_ID') || '';

  if (!apiKey) {
    console.error('❌  FIREBASE_API_KEY not found in environment.');
    console.error('    Go to Vercel → Project → Settings → Environment Variables');
    console.error('    and make sure FIREBASE_API_KEY is set.\n');
    // Don't exit with error — let Vercel deploy continue; firebase-config.js
    // will keep its placeholder values and show a clear console error at runtime.
    return;
  }

  const out = `// firebase-config.js
// AUTO-GENERATED by build.js on ${new Date().toISOString()}
// Do NOT edit manually — values come from Vercel Environment Variables.
window.__FIREBASE_CONFIG__ = {
  apiKey:            "${apiKey}",
  authDomain:        "${authDomain}",
  projectId:         "${projectId}",
  storageBucket:     "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId:             "${appId}",
  measurementId:     "${measurementId}"
};
`;

  fs.writeFileSync(path.join(__dirname, 'firebase-config.js'), out, 'utf8');
  console.log('  ✅ firebase-config.js written with real credentials');

  const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
  console.log(`\n✅ Build complete — ConfFlow v${pkg.version}`);
  console.log('🌐 Vercel will serve the output directory.\n');
}

build();
