// firebase-config.js
// ─────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED by build.js during Vercel deployment.
// The real values are injected from Vercel Environment Variables.
//
// For LOCAL development:
//   Replace the placeholder values below with your real Firebase credentials.
//   Get them from: Firebase Console → Project Settings → Your Apps → Config
//
// ⚠️  Never commit real API keys to a public repo.
//     Keep this file with placeholders in git; Vercel injects real values at build time.
// ─────────────────────────────────────────────────────────

window.__FIREBASE_CONFIG__ = {
  apiKey:            "PLACEHOLDER_REPLACED_BY_BUILD",
  authDomain:        "confflow-bcfb4.firebaseapp.com",
  projectId:         "confflow-bcfb4",
  storageBucket:     "confflow-bcfb4.firebasestorage.app",
  messagingSenderId: "100137392506",
  appId:             "PLACEHOLDER_REPLACED_BY_BUILD",
  measurementId:     "PLACEHOLDER_REPLACED_BY_BUILD"
};
